### ISSUE TITLE
The page was loaded over HTTPS, but insecure stylesheet

### ISSUE THREAD

**Issue by NatMota** [ONSvisual/ONSvisual.github.io#1]
Hi,

Couldn't link your resource found at http://visual.ons.gov.uk/no-money-no-medals/ unfortunately. Wordpress is not loading it with an iframe plugin. This is what the console says: 

"Mixed Content: The page at 'https://onsvisual.github.io/dvc354/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Open+Sans:400,300,600|Open+Sans+Condensed:300'. This request has been blocked; the content must be served over HTTPS."

It's unfortunate that there seems to only be a problem with the style-sheet.
If you could help with this I would deeply appreciate it. 

Thank you,
Natanael

**Comment by zoehartland** [comment]
Hi Natanael, 

I think I've resolved this for you. Is it working?

Zoe

**Comment by NatMota** [comment]
Hi Zoe,

Thanks, sadly it's still the same. I have solved the problem somewhat by taking a screenshot and linking to your site.

Natanael
